apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-CICD-webapp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "kubernetes-CICD-webapp.name" . }}